import { get, onValue, ref, runTransaction, serverTimestamp, set, update, type Unsubscribe } from 'firebase/database';
import { seedTeams, debugQuestions, type DebugQuestion, type SeedTeam } from '@/data/competition';
import { getFirebaseDatabase } from '@/lib/firebase-client';
export type RoundConfig = { durationSeconds:number; questionDurationSeconds:number; questionCount:number };
export type TeamRecord = SeedTeam & { status:'connected'|'in-progress'|'submitted'; connectedAt?:number; lastSeenAt?:number; runId?:string; questionOrder?:number[]; answers?:Record<string,string>; recovery?:number; corruption?:number; integrity?:number; netScore?:number; totalTimeSeconds?:number; submittedAt?:number; advanced?:boolean; phase1StartedAt?:number };
export type CompetitionControl = { command:'standby'|'breach'|'phase1-start'|'phase1-pause'|'phase1-resume'|'phase1-restart'|'results'|'reset'; issuedAt?:number; runId?:string; phase1StartedAt?:number; phase1DurationSeconds?:number; pausedAt?:number };
const teamPath=(teamCode:string)=>`teams/${encodeURIComponent(teamCode.trim().toUpperCase())}`;
export const DEFAULT_ROUND1_CONFIG:RoundConfig={durationSeconds:840,questionDurationSeconds:35,questionCount:30};
export async function getCompetitionControl(){const db=await getFirebaseDatabase();if(!db)return null;try{return((await get(ref(db,'competition/control'))).val() as CompetitionControl|null)??null}catch{return null}}
export async function ensureTeamsSeeded(){const db=await getFirebaseDatabase();if(!db)return false;try{await Promise.all(seedTeams.map(t=>runTransaction(ref(db,teamPath(t.teamCode)),c=>c??{...t,status:'connected',answers:{},recovery:0,corruption:0,integrity:0,netScore:0,advanced:false})));await ensureRound1Seeded();return true}catch(e){console.warn('[breaking-bug] Firebase seed failed.',e);return false}}
export async function ensureRound1Seeded(){const db=await getFirebaseDatabase();if(!db)return false;const qRef=ref(db,'rounds/1/questions');const cRef=ref(db,'rounds/1/config');try{await runTransaction(qRef,current=>current??Object.fromEntries(debugQuestions.slice(0,30).map(q=>[q.id,q])));await runTransaction(cRef,current=>current??DEFAULT_ROUND1_CONFIG);return true}catch(e){console.warn('[breaking-bug] Round seed failed.',e);return false}}
export async function getRoundQuestions(round=1){const db=await getFirebaseDatabase();if(!db)return debugQuestions;try{const v=(await get(ref(db,`rounds/${round}/questions`))).val();if(!v)return debugQuestions;return Object.values(v) as DebugQuestion[]}catch{return debugQuestions}}
export async function getRoundConfig(round=1){const db=await getFirebaseDatabase();if(!db)return DEFAULT_ROUND1_CONFIG;try{return((await get(ref(db,`rounds/${round}/config`))).val() as RoundConfig|null)??DEFAULT_ROUND1_CONFIG}catch{return DEFAULT_ROUND1_CONFIG}}
export async function saveRoundQuestions(round:number,questions:DebugQuestion[]){const db=await getFirebaseDatabase();if(!db)return;await set(ref(db,`rounds/${round}/questions`),Object.fromEntries(questions.map(q=>[q.id,q])))}
export async function saveRoundConfig(round:number,config:RoundConfig){const db=await getFirebaseDatabase();if(!db)return;await set(ref(db,`rounds/${round}/config`),config)}
export async function authenticateTeam(teamCode:string,accessKey:string){await ensureTeamsSeeded();const db=await getFirebaseDatabase();if(!db)return null;try{const r=(await get(ref(db,teamPath(teamCode)))).val() as TeamRecord|null;return r&&r.accessKey===accessKey.trim().toUpperCase()?r:null}catch{return null}}
export async function getTeam(teamCode:string){const db=await getFirebaseDatabase();if(!db)return null;try{return(await get(ref(db,teamPath(teamCode)))).val() as TeamRecord|null}catch{return null}}
export async function updateTeam(teamCode:string,patch:Partial<TeamRecord>){const db=await getFirebaseDatabase();if(!db)return;try{await update(ref(db,teamPath(teamCode)),patch)}catch(e){console.warn('[breaking-bug] Team update failed.',e)}}
export function watchTeam(teamCode:string,onTeam:(team:TeamRecord|null)=>void):Unsubscribe{let stop:Unsubscribe=()=>undefined;void getFirebaseDatabase().then(db=>{if(!db)return;stop=onValue(ref(db,teamPath(teamCode)),s=>onTeam(s.val() as TeamRecord|null))});return()=>stop()}
export function watchTeams(onTeams:(teams:TeamRecord[])=>void):Unsubscribe{let stop:Unsubscribe=()=>undefined;void getFirebaseDatabase().then(db=>{if(!db)return;stop=onValue(ref(db,'teams'),s=>{const v=s.val() as Record<string,TeamRecord>|null;onTeams(v?Object.values(v).sort((a,b)=>a.teamCode.localeCompare(b.teamCode)):[])})});return()=>stop()}
export function watchRoundQuestions(round:number,onQuestions:(q:DebugQuestion[])=>void):Unsubscribe{let stop:Unsubscribe=()=>undefined;void getFirebaseDatabase().then(db=>{if(!db)return;stop=onValue(ref(db,`rounds/${round}/questions`),s=>{const v=s.val();onQuestions(v?Object.values(v) as DebugQuestion[]:[])})});return()=>stop()}
export async function writeControl(command:CompetitionControl['command'],extra:Partial<CompetitionControl>={}){const db=await getFirebaseDatabase();if(!db)return;await set(ref(db,'competition/control'),{command,runId:`${Date.now()}-${Math.random().toString(36).slice(2,8)}`,issuedAt:serverTimestamp(),...extra})}
export async function startSharedPhaseOne(){const db=await getFirebaseDatabase();if(!db)return;const cfg=await getRoundConfig(1);const now=Date.now();await set(ref(db,'competition/control'),{command:'phase1-start',runId:`${now}-${Math.random().toString(36).slice(2,8)}`,issuedAt:serverTimestamp(),phase1StartedAt:now,phase1DurationSeconds:cfg.durationSeconds});await Promise.all(seedTeams.map(t=>update(ref(db,teamPath(t.teamCode)),{phase1StartedAt:now,status:'in-progress'})))}
export async function pauseSharedPhaseOne(){const db=await getFirebaseDatabase();if(!db)return;await update(ref(db,'competition/control'),{command:'phase1-pause',pausedAt:Date.now(),issuedAt:serverTimestamp()})}
export async function resumeSharedPhaseOne(){const db=await getFirebaseDatabase();if(!db)return;const s=await get(ref(db,'competition/control'));const c=s.val() as CompetitionControl|null;if(!c?.pausedAt||!c.phase1StartedAt)return;const shifted=c.phase1StartedAt+(Date.now()-c.pausedAt);await update(ref(db,'competition/control'),{command:'phase1-resume',phase1StartedAt:shifted,pausedAt:null,issuedAt:serverTimestamp()});await Promise.all(seedTeams.map(t=>update(ref(db,teamPath(t.teamCode)),{phase1StartedAt:shifted})))}
export async function restartSharedPhaseOne(){await startSharedPhaseOne()}
export async function saveTeamAnswer(teamCode:string,questionId:number,answer:string,runId?:string){const db=await getFirebaseDatabase();if(!db)return;await update(ref(db,teamPath(teamCode)),{[`answers/${questionId}`]:answer,...(runId?{runId}:{})})}
export async function submitTeamPhaseOne(teamCode:string,summary:{recovery:number;corruption:number;integrity:number;netScore:number;totalTimeSeconds:number}){const db=await getFirebaseDatabase();if(!db)return;await update(ref(db,teamPath(teamCode)),{...summary,status:'submitted',submittedAt:serverTimestamp()})}
export async function computePhaseOneResults(){const db=await getFirebaseDatabase();if(!db)return[];const values=(await get(ref(db,'teams'))).val() as Record<string,TeamRecord>|null;const submitted=values?Object.values(values).filter(t=>t.status==='submitted').sort((a,b)=>(b.integrity??0)-(a.integrity??0)||(a.totalTimeSeconds??Infinity)-(b.totalTimeSeconds??Infinity)):[];const finalists=new Set(submitted.slice(0,25).map(t=>t.teamCode));await Promise.all(seedTeams.map(t=>update(ref(db,teamPath(t.teamCode)),{advanced:finalists.has(t.teamCode)})));await writeControl('results');return submitted}
export async function resetCompetition(){const db=await getFirebaseDatabase();if(!db)return;await Promise.all(seedTeams.map(t=>set(ref(db,teamPath(t.teamCode)),{...t,status:'connected',answers:{},recovery:0,corruption:0,integrity:0,netScore:0,advanced:false})));await writeControl('reset')}
