import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { debugQuestions, type DebugQuestion } from '@/data/competition';
import { authenticateTeam, getCompetitionControl, getRoundConfig, getRoundQuestions, getTeam, saveTeamAnswer, submitTeamPhaseOne, updateTeam, watchTeam } from '@/lib/firebase';
import { publishTakeoverEvent, realtime } from '@/services/realtime';
export type ParticipantStage='access'|'authenticating'|'standby'|'anomaly'|'breach'|'takeover'|'transmission'|'phase1'|'results'|'mission'|'chambers'|'restored';
const sessionKey=(t:string)=>`breaking-bug:team:${t}`;
function shuffle(q:DebugQuestion[],team:string){const a=[...q];let seed=[...team].reduce((s,c)=>(s*31+c.charCodeAt(0))>>>0,7);for(let i=a.length-1;i>0;i--){seed=(seed*1664525+1013904223)>>>0;const j=seed%(i+1);[a[i],a[j]]=[a[j],a[i]];}return a;}
export function useCompetition(){
 const [stage,setStage]=useState<ParticipantStage>('access'),[team,setTeam]=useState(''),[questions,setQuestions]=useState<DebugQuestion[]>([]),[questionIndex,setQuestionIndex]=useState(0),[answers,setAnswers]=useState<Record<number,string>>({}),[overallSeconds,setOverallSeconds]=useState(840),[questionSeconds,setQuestionSeconds]=useState(35),[breachStep,setBreachStep]=useState(0),[questionReady,setQuestionReady]=useState(false),[authError,setAuthError]=useState(''),[advanced,setAdvanced]=useState(false),[phase1StartedAt,setPhase1StartedAt]=useState<number|null>(null),[questionStartedAt,setQuestionStartedAt]=useState<number|null>(null),[paused,setPaused]=useState(false),[config,setConfig]=useState({durationSeconds:840,questionDurationSeconds:35,questionCount:30});
 const stageRef=useRef(stage),teamRef=useRef(team),phase1FinalizedRef=useRef(false),answersRef=useRef(answers),overallSecondsRef=useRef(overallSeconds);stageRef.current=stage;teamRef.current=team;answersRef.current=answers;overallSecondsRef.current=overallSeconds;
 const persist=useCallback((t:string,s:ParticipantStage)=>{if(typeof window!=='undefined')sessionStorage.setItem(sessionKey(t),JSON.stringify({teamCode:t,stage:s}))},[]);
 const reset=useCallback(()=>{phase1FinalizedRef.current=false;if(teamRef.current)sessionStorage.removeItem(sessionKey(teamRef.current));setStage('access');setTeam('');setQuestions([]);setQuestionIndex(0);setAnswers({});setOverallSeconds(840);setQuestionSeconds(35);setBreachStep(0);setQuestionReady(false);setAuthError('');setAdvanced(false);setPhase1StartedAt(null);setQuestionStartedAt(null);setPaused(false)},[]);
 const finalizePhaseOne=useCallback(()=>{if(phase1FinalizedRef.current||!teamRef.current)return;phase1FinalizedRef.current=true;const correct=questions.reduce((n,q)=>n+(answersRef.current[q.id]===q.answer?1:0),0),integrity=questions.length?Math.round(correct/questions.length*100):0,wrong=questions.length-correct,totalTimeSeconds=Math.max(0,config.durationSeconds-overallSecondsRef.current);void submitTeamPhaseOne(teamRef.current,{recovery:correct,corruption:wrong,integrity,netScore:integrity,totalTimeSeconds}).catch(error=>{console.error('[breaking-bug] Phase 1 finalization failed.',error)});setOverallSeconds(0);setStage('results');persist(teamRef.current,'results')},[config.durationSeconds,persist,questions]);
 const beginTakeover=useCallback(()=>{publishTakeoverEvent('breach_start');publishTakeoverEvent('system_glitch');setStage('anomaly');setBreachStep(0);if(teamRef.current)void updateTeam(teamRef.current,{status:'in-progress'})},[]);
 useEffect(()=>realtime.connect(m=>{if(m.type==='breach'&&(stageRef.current==='standby'||stageRef.current==='access'))beginTakeover();if(m.type==='reset')reset();if(m.type==='phase1-start'&&m.phase1StartedAt){phase1FinalizedRef.current=false;setPhase1StartedAt(m.phase1StartedAt);setQuestionStartedAt(null);setPaused(false);setStage('phase1');persist(teamRef.current,'phase1')}if(m.type==='phase1-pause')setPaused(true);if(m.type==='phase1-resume'&&m.phase1StartedAt){setPhase1StartedAt(m.phase1StartedAt);setQuestionStartedAt(null);setPaused(false);setStage('phase1')}if(m.type==='results')setStage('results')}),[beginTakeover,persist,reset]);
 useEffect(()=>{if(!team)return;return watchTeam(team,r=>{if(!r)return;setAdvanced(Boolean(r.advanced));if(r.answers)setAnswers(Object.fromEntries(Object.entries(r.answers).map(([k,v])=>[Number(k),v])));if(r.phase1StartedAt)setPhase1StartedAt(r.phase1StartedAt);if(r.status==='submitted')setStage('results')})},[team]);
 useEffect(()=>{if(!team)return;const heartbeat=window.setInterval(()=>{void updateTeam(teamRef.current,{lastSeenAt:Date.now()})},15000);return()=>window.clearInterval(heartbeat)},[team]);
 useEffect(()=>{let dead=false;(async()=>{if(typeof window==='undefined')return;const key=Object.keys(sessionStorage).find(k=>k.startsWith('breaking-bug:team:'));if(!key)return;const saved=JSON.parse(sessionStorage.getItem(key)||'{}') as {teamCode?:string};if(!saved.teamCode)return;try{const [r,c,qs]=await Promise.all([getTeam(saved.teamCode),getCompetitionControl(),getRoundQuestions(1)]);if(dead||!r)return;const cfg=await getRoundConfig(1);setTeam(r.teamCode);setQuestions(shuffle(qs.length?qs:debugQuestions,r.teamCode).slice(0,cfg.questionCount||30));setAnswers(Object.fromEntries(Object.entries(r.answers??{}).map(([k,v])=>[Number(k),v])));setAdvanced(Boolean(r.advanced));setConfig(cfg);setPhase1StartedAt(r.phase1StartedAt??c?.phase1StartedAt??null);const activePhase=c?.command==='phase1-start'||c?.command==='phase1-pause'||c?.command==='phase1-resume'||Boolean(r.phase1StartedAt);setPaused(c?.command==='phase1-pause');setStage(activePhase?'phase1':r.status==='submitted'?'results':'standby')}catch(error){console.error('[breaking-bug] Session recovery failed.',error)}})();return()=>{dead=true}},[]);
 useEffect(()=>{if(stage!=='anomaly')return;const t=setTimeout(()=>setStage('breach'),1250);return()=>clearTimeout(t)},[stage]);
 useEffect(()=>{if(stage!=='breach')return;const t=setInterval(()=>setBreachStep(s=>{if(s>=4){clearInterval(t);setStage('takeover');return s}return s+1}),500);return()=>clearInterval(t)},[stage]);
 useEffect(()=>{if(stage==='breach'&&breachStep===2)publishTakeoverEvent('critical_alert')},[breachStep,stage]);
 useEffect(()=>{if(stage!=='takeover')return;const t=setTimeout(()=>{publishTakeoverEvent('message_typing');setStage('transmission')},950);return()=>clearTimeout(t)},[stage]);
 useEffect(()=>{if(stage!=='phase1')return;setQuestionReady(false);setQuestionStartedAt(null);const t=setTimeout(()=>setQuestionReady(true),1350);return()=>clearTimeout(t)},[questionIndex,stage]);
 useEffect(()=>{if(stage!=='phase1'||!phase1StartedAt||paused)return;const tick=()=>{const elapsed=Math.max(0,Math.floor((Date.now()-phase1StartedAt)/1000));const remaining=Math.max(0,config.durationSeconds-elapsed);setOverallSeconds(remaining);if(remaining<=0){finalizePhaseOne();return}if(questionReady&&questionStartedAt){const questionElapsed=Math.max(0,Math.floor((Date.now()-questionStartedAt)/1000));setQuestionSeconds(Math.max(0,config.questionDurationSeconds-questionElapsed))}};tick();const t=setInterval(tick,250);return()=>clearInterval(t)},[config.durationSeconds,config.questionDurationSeconds,finalizePhaseOne,paused,phase1StartedAt,questionReady,questionStartedAt,stage]);
 useEffect(()=>{if(stage!=='phase1'||!questionReady||paused)return;const startedAt=Date.now();setQuestionStartedAt(startedAt);setQuestionSeconds(config.questionDurationSeconds)},[config.questionDurationSeconds,paused,questionIndex,questionReady,stage]);
 const authenticate=useCallback(async(code:string,key:string)=>{setAuthError('');setStage('authenticating');try{const r=await authenticateTeam(code,key);if(!r){setAuthError('Credentials rejected. Check the team code and access key.');setStage('access');return}phase1FinalizedRef.current=false;const [qs,cfg]=await Promise.all([getRoundQuestions(1),getRoundConfig(1)]);const ordered=shuffle(qs.length?qs:debugQuestions,r.teamCode).slice(0,cfg.questionCount||30);setTeam(r.teamCode);setQuestions(ordered);setAnswers(Object.fromEntries(Object.entries(r.answers??{}).map(([k,v])=>[Number(k),v])));setAdvanced(Boolean(r.advanced));setConfig(cfg);setPhase1StartedAt(r.phase1StartedAt??null);setQuestionStartedAt(null);void updateTeam(r.teamCode,{status:'connected',connectedAt:Date.now(),lastSeenAt:Date.now(),questionOrder:ordered.map(q=>q.id)});persist(r.teamCode,'standby');setTimeout(()=>setStage('standby'),600)}catch(error){const message=error instanceof Error?error.message:String(error);console.error('[breaking-bug] Team authentication failed.',error);setAuthError(message);setStage('access')}},[persist]);
 const answer=useCallback((value:string)=>{const q=questions[questionIndex];if(!q||answers[q.id]||!questionReady||questionSeconds<=0||overallSeconds<=0)return;setAnswers(a=>({...a,[q.id]:value}));void saveTeamAnswer(teamRef.current,q.id,value)},[answers,overallSeconds,questionIndex,questionReady,questionSeconds,questions]);
 const nextQuestion=useCallback(()=>{if(overallSeconds<=0){finalizePhaseOne();return}if(questionIndex>=questions.length-1){finalizePhaseOne();return}setQuestionIndex(i=>i+1);setQuestionSeconds(config.questionDurationSeconds);setQuestionStartedAt(null);setQuestionReady(false);persist(teamRef.current,'phase1')},[config.questionDurationSeconds,finalizePhaseOne,overallSeconds,persist,questionIndex,questions.length]);
 const completeTransmission=useCallback(()=>{publishTakeoverEvent('message_complete');setStage('standby')},[]);
 const startMission=useCallback(()=>{if(advanced){setStage('mission');persist(teamRef.current,'mission')}},[advanced,persist]);
 const enterChambers=useCallback(()=>setStage('chambers'),[]),finish=useCallback(()=>setStage('restored'),[]),correct=useMemo(()=>questions.reduce((n,q)=>n+(answers[q.id]===q.answer?1:0),0),[answers,questions]);
 return {stage,team,questions,questionIndex,answers,overallSeconds,questionSeconds,breachStep,questionReady,correct,answered:Object.keys(answers).length,advanced,authError,authenticate,answer,nextQuestion,completeTransmission,startMission,enterChambers,finish,reset,integrity:questions.length?Math.round(correct/questions.length*100):0,config,demoMode:false,setDemoMode:()=>undefined};
}
