import { useEffect, useMemo, useState } from 'react';
import { Activity, ChevronRight, Plus, RotateCcw, Save, ShieldAlert, Trash2, Trophy, Users } from 'lucide-react';
import { computePhaseOneResults, ensureTeamsSeeded, getRoundConfig, getRoundQuestions, resetCompetition, saveRoundConfig, saveRoundQuestions, startSharedPhaseOne, pauseSharedPhaseOne, resumeSharedPhaseOne, restartSharedPhaseOne, watchTeams, type TeamRecord, type RoundConfig } from '@/lib/firebase';
import { realtime } from '@/services/realtime';
import { debugQuestions, type DebugQuestion } from '@/data/competition';
import { Button, Label, SystemFrame } from '@/components/system-frame';

const emptyQuestion=(id:number):DebugQuestion=>({id,topic:'New challenge',code:'// insert code',prompt:'What is the safest correction?',options:[{id:'A',label:'Option A'},{id:'B',label:'Option B'},{id:'C',label:'Option C'},{id:'D',label:'Option D'}],answer:'A'});
function ranked(teams:TeamRecord[]){return teams.filter(t=>t.status==='submitted').sort((a,b)=>(b.integrity??0)-(a.integrity??0)||(a.totalTimeSeconds??Infinity)-(b.totalTimeSeconds??Infinity));}
export function AdminPage(){
 const [tab,setTab]=useState<'Round 1'|'Round 2'|'Round 3'|'Overview'>('Round 1'),[teams,setTeams]=useState<TeamRecord[]>([]),[questions,setQuestions]=useState<DebugQuestion[]>(debugQuestions),[config,setConfig]=useState<RoundConfig>({durationSeconds:840,questionDurationSeconds:35,questionCount:30}),[saving,setSaving]=useState(false),[status,setStatus]=useState('ARMED'),[paused,setPaused]=useState(false),[confirmReset,setConfirmReset]=useState(false),[actionError,setActionError]=useState('');
 useEffect(()=>{void ensureTeamsSeeded().catch(error=>setActionError(error instanceof Error?error.message:'Firebase initialization failed.'));const stop=watchTeams(setTeams);void Promise.all([getRoundQuestions(1),getRoundConfig(1)]).then(([q,c])=>{setQuestions(q.length?q:debugQuestions);setConfig(c)}).catch(error=>setActionError(error instanceof Error?error.message:'Failed to load Round 1 configuration.'));const un=realtime.connect(m=>{if(m.type==='breach')setStatus('BREACH DISPATCHED');if(m.type==='phase1-start')setStatus('PHASE 1 LIVE');if(m.type==='phase1-pause'){setPaused(true);setStatus('PAUSED')}if(m.type==='phase1-resume'){setPaused(false);setStatus('PHASE 1 LIVE')}if(m.type==='results')setStatus('RESULTS READY');if(m.type==='reset')setStatus('ARMED')});return()=>{stop();un()}},[]);
 const connected=teams.filter(t=>Boolean(t.connectedAt)).length,inProgress=teams.filter(t=>t.status==='in-progress').length,submitted=teams.filter(t=>t.status==='submitted').length,ranking=useMemo(()=>ranked(teams),[teams]);
 const runAction=async(action:()=>Promise<void>,fallback='Organizer action failed.')=>{setActionError('');try{await action()}catch(error){const message=error instanceof Error?error.message:fallback;console.error('[breaking-bug] Admin action failed.',error);setActionError(message)}};
 const dispatch=()=>{setActionError('');try{realtime.publish({type:'breach',issuedAt:Date.now(),source:'organizer'});setStatus('BREACH DISPATCHED')}catch(error){setActionError(error instanceof Error?error.message:'Failed to dispatch breach.')}};
 const begin=()=>void runAction(async()=>{await startSharedPhaseOne();setStatus('PHASE 1 LIVE')},'Failed to start Phase 1.');
 const save=async()=>{setSaving(true);setActionError('');try{await saveRoundQuestions(1,questions);await saveRoundConfig(1,config)}catch(error){const message=error instanceof Error?error.message:'Failed to save Round 1 configuration.';console.error('[breaking-bug] Round 1 save failed.',error);setActionError(message)}finally{setSaving(false)}};
 const updateQ=(id:number,patch:Partial<DebugQuestion>)=>setQuestions(qs=>qs.map(q=>q.id===id?{...q,...patch}:q));
 return <SystemFrame step="00" eyebrow="ORGANIZER CONTROL"><section className="flex flex-1 flex-col py-3"><div className="flex flex-col justify-between gap-5 border-b border-[hsl(var(--border))] pb-6 md:flex-row md:items-end"><div><Label>Organizer console / command layer</Label><h1 className="mt-4 text-4xl font-medium tracking-[-.05em] text-[#e7e1d2] md:text-6xl">Control room.</h1><p className="mt-3 max-w-xl text-sm leading-6 text-dim">One source of truth. Organizer-owned timing. Live integrity ranking.</p></div><div className="font-mono text-[10px] uppercase tracking-[.12em] text-secure"><span className="status-dot status-dot-green mr-2" />{status}</div></div>
 {actionError&&<div role="alert" className="mt-5 flex items-start gap-3 border border-[#a34b48] bg-[rgba(126,45,43,.12)] p-4 text-xs text-[#c66b65]"><ShieldAlert size={15} className="mt-0.5 shrink-0"/><div><div className="font-mono text-[9px] uppercase tracking-[.1em]">Action failed</div><p className="mt-1 leading-5">{actionError}</p></div></div>}
 <div className="mt-6 flex flex-wrap gap-2">{(['Round 1','Round 2','Round 3','Overview'] as const).map(t=><button key={t} onClick={()=>setTab(t)} className={`border px-4 py-2 font-mono text-[10px] uppercase tracking-[.1em] ${tab===t?'border-[#8ca793] text-secure':'border-[hsl(var(--border))] text-dim'}`}>{t}</button>)}</div>
 {tab==='Round 1'&&<div className="mt-6 grid gap-6 lg:grid-cols-[1.3fr_.7fr]"><div className="system-card p-5"><div className="flex items-center justify-between"><div><Label>Question editor / Round 1</Label><p className="mt-2 text-xs text-dim">Firebase is the source of truth. Correct option is explicit.</p></div><Button testId="admin-action" onClick={()=>setQuestions(q=>[...q,emptyQuestion((q.at(-1)?.id??0)+1)])}><Plus size={13} className="mr-2 inline"/>Add</Button></div><div className="mt-5 space-y-4">{questions.map((q,i)=><div key={q.id} className="border border-[hsl(var(--border))] p-4"><div className="flex items-center justify-between"><span className="font-mono text-[10px] text-secure">Q{String(i+1).padStart(2,'0')}</span><button onClick={()=>setQuestions(qs=>qs.filter(x=>x.id!==q.id))} className="text-breach"><Trash2 size={14}/></button></div><input value={q.topic} onChange={e=>updateQ(q.id,{topic:e.target.value})} className="input-system mt-3 w-full px-3 py-2 text-xs" placeholder="Topic"/><textarea value={q.prompt} onChange={e=>updateQ(q.id,{prompt:e.target.value})} className="input-system mt-2 min-h-16 w-full px-3 py-2 text-xs"/><textarea value={q.code} onChange={e=>updateQ(q.id,{code:e.target.value})} className="input-system mt-2 min-h-16 w-full px-3 py-2 font-mono text-xs"/><div className="mt-3 grid gap-2 md:grid-cols-2">{q.options.map(o=><div key={o.id} className="flex gap-2"><span className="pt-2 font-mono text-[10px] text-dim">{o.id}</span><input value={o.label} onChange={e=>updateQ(q.id,{options:q.options.map(x=>x.id===o.id?{...x,label:e.target.value}:x)})} className="input-system w-full px-3 py-2 text-xs"/></div>)}</div><select value={q.answer} onChange={e=>updateQ(q.id,{answer:e.target.value})} className="input-system mt-3 px-3 py-2 font-mono text-xs">{q.options.map(o=><option key={o.id} value={o.id}>Correct: {o.id}</option>)}</select></div>)}</div></div>
 <div className="space-y-6"><div className="system-card p-5"><Label>Timer config</Label><div className="mt-4 grid gap-3"><label className="font-mono text-[10px] text-dim">ROUND SECONDS<input type="number" value={config.durationSeconds} onChange={e=>setConfig({...config,durationSeconds:Number(e.target.value)})} className="input-system mt-1 w-full px-3 py-2 text-xs"/></label><label className="font-mono text-[10px] text-dim">QUESTION SECONDS<input type="number" value={config.questionDurationSeconds} onChange={e=>setConfig({...config,questionDurationSeconds:Number(e.target.value)})} className="input-system mt-1 w-full px-3 py-2 text-xs"/></label><label className="font-mono text-[10px] text-dim">QUESTION COUNT<input type="number" value={config.questionCount} onChange={e=>setConfig({...config,questionCount:Number(e.target.value)})} className="input-system mt-1 w-full px-3 py-2 text-xs"/></label></div><Button testId="admin-action" onClick={()=>void save()} disabled={saving}><Save size={13} className="mr-2 inline"/>{saving?'Saving...':'Save to Firebase'}</Button></div>
 <div className="system-card p-5"><Label>Round controls</Label><div className="mt-4 grid gap-2"><Button testId="admin-dispatch" variant="danger" onClick={dispatch}>Initiate breach <ChevronRight size={13} className="ml-2 inline"/></Button><Button testId="admin-action" onClick={begin}>Begin Phase 1</Button><div className="grid grid-cols-2 gap-2"><Button testId="admin-pause" variant="quiet" onClick={()=>void runAction(async()=>{await pauseSharedPhaseOne();setPaused(true);setStatus('PAUSED')},'Failed to pause Phase 1.')} disabled={paused}>Pause</Button><Button testId="admin-resume" variant="quiet" onClick={()=>void runAction(async()=>{await resumeSharedPhaseOne();setPaused(false);setStatus('PHASE 1 LIVE')},'Failed to resume Phase 1.')} disabled={!paused}>Resume</Button></div><Button testId="admin-restart" variant="quiet" onClick={()=>void runAction(async()=>{await restartSharedPhaseOne();setPaused(false);setStatus('PHASE 1 LIVE')},'Failed to restart Phase 1.')}><RotateCcw size={13} className="mr-2 inline"/>Restart round</Button><Button testId="admin-action" onClick={()=>void runAction(async()=>{await computePhaseOneResults();setStatus('RESULTS READY')},'Failed to compute Phase 1 results.')}><Trophy size={13} className="mr-2 inline"/>Compute top 25</Button></div></div></div></div>}
 {tab==='Overview'&&<Overview teams={teams} ranking={ranking} connected={connected} inProgress={inProgress} submitted={submitted} confirmReset={confirmReset} setConfirmReset={setConfirmReset} runAction={runAction}/>} 
 {tab!=='Round 1'&&tab!=='Overview'&&<div className="system-card mt-6 p-8"><Label>{tab}</Label><h2 className="mt-4 text-2xl text-[#e7e1d2]">Round shell ready.</h2><p className="mt-3 max-w-xl text-sm leading-6 text-dim">The same organizer controls and Firebase-backed question architecture are ready to be populated when Round 2 and Round 3 mechanics are finalized.</p></div>}
 </section></SystemFrame>;
}
function Overview({teams,ranking,connected,inProgress,submitted,confirmReset,setConfirmReset,runAction}:{teams:TeamRecord[];ranking:TeamRecord[];connected:number;inProgress:number;submitted:number;confirmReset:boolean;setConfirmReset:(v:boolean)=>void;runAction:(action:()=>Promise<void>,fallback?:string)=>Promise<void>}){return <div className="mt-6 grid gap-6 lg:grid-cols-[.8fr_1.2fr]"><div className="system-card p-6"><Label>Live status</Label><div className="mt-5 grid grid-cols-2 gap-px border border-[hsl(var(--border))] bg-[hsl(var(--border))]"><Info label="Connected" value={String(connected)}/><Info label="In progress" value={String(inProgress)}/><Info label="Submitted" value={String(submitted)}/><Info label="Advanced" value={String(teams.filter(t=>t.advanced).length)}/></div><div className="mt-8 border-t border-[hsl(var(--border))] pt-5"><Button testId="admin-reset-open" variant="danger" onClick={()=>setConfirmReset(true)}><RotateCcw size={13} className="mr-2 inline"/>Reset everything</Button></div></div><div className="system-card p-6"><Label>Phase 1 leaderboard / Integrity</Label><div className="mt-5 space-y-1 font-mono text-[10px]">{ranking.map((t,i)=><div key={t.teamCode}>{i===25&&<div className="my-2 border-y border-[#a34b48] py-2 text-center text-[#c66b65]">— KILL LINE —</div>}<div className={`flex justify-between border-b border-[hsl(var(--border))] py-3 ${i>=25?'opacity-45 line-through':''}`}><span><span className="mr-3 text-dim">{String(i+1).padStart(2,'0')}</span>{t.name}</span><span className="text-secure">{t.integrity??0}% <span className="text-dim">{t.recovery??0}/{(t.recovery??0)+(t.corruption??0)} • {t.totalTimeSeconds??0}s</span></span></div></div>)}{ranking.length===0&&<p className="text-dim">No submitted teams yet.</p>}</div></div>{confirmReset&&<div className="fixed inset-0 z-20 grid place-items-center bg-black/80 p-5"><div className="system-card max-w-md p-6"><h2 className="text-xl text-[#e7e1d2]">Reset all competition state?</h2><p className="mt-3 text-sm text-dim">This clears team answers, rankings and phase state.</p><div className="mt-6 flex justify-end gap-2"><Button testId="admin-reset-cancel" variant="quiet" onClick={()=>setConfirmReset(false)}>Cancel</Button><Button testId="admin-reset-confirm" variant="danger" onClick={()=>void runAction(async()=>{await resetCompetition();setConfirmReset(false);setStatus('ARMED')},'Failed to reset competition state.')}>Confirm reset</Button></div></div></div>}</div>}
function Info({label,value}:{label:string;value:string}){return <div className="bg-[#111719] p-4"><div className="font-mono text-[9px] uppercase text-dim">{label}</div><div className="mt-2 font-mono text-lg text-[#d8d0bb]">{value}</div></div>}
