import { type ReactNode } from 'react';
import { ShieldCheck, Wifi } from 'lucide-react';

export function SystemFrame({ children, tone = 'secure', eyebrow = 'ACCESS PORTAL', step = '01', alarm = false }: { children: ReactNode; tone?: 'secure' | 'breach' | 'anomaly'; eyebrow?: string; step?: string; alarm?: boolean }) {
  const breach = tone === 'breach'; const anomaly = tone === 'anomaly';
  return <main className={`shell ${breach ? 'shell-breach' : anomaly ? 'shell-anomaly' : ''} ${alarm ? 'integrity-low' : ''} flex min-h-[100dvh] flex-col px-5 py-5 md:px-10 md:py-7`}><header className="mx-auto flex w-full max-w-[1240px] items-center justify-between border-b border-[hsl(var(--border))] pb-5"><div className="flex items-center gap-3"><div className={`grid h-8 w-8 place-items-center border ${breach ? 'border-[#8d3738]' : anomaly ? 'border-[#97644f]' : 'border-[#667f70]'}`}><span className={`block h-3 w-3 border ${breach ? 'border-[#bd514c]' : anomaly ? 'border-[#bd795c]' : 'border-[#9bb69e]'}`} /></div><div><div className="font-mono text-[11px] tracking-[.18em] text-[#e6e0d0]">BREAKING BUG</div><div className="font-mono text-[9px] tracking-[.12em] text-dim">SECURE COMPETITION CHANNEL</div></div></div><div className={`flex items-center gap-2 font-mono text-[10px] tracking-[.12em] ${breach || anomaly ? 'text-breach' : 'text-secure'}`}><span className={`status-dot ${breach || anomaly ? 'status-dot-red' : 'status-dot-green'}`} />{breach ? 'INTRUSION ACTIVE' : anomaly ? 'CHANNEL INTERRUPTED' : 'SYSTEM SECURE'}</div></header><div className="mx-auto flex w-full max-w-[1240px] flex-1 flex-col"><div className="flex items-center justify-between py-5 font-mono text-[10px] uppercase tracking-[.14em] text-dim"><span>{step} / {eyebrow}</span><span className="hidden md:block">BBX / 24.09 / INTERNAL</span></div>{children}</div><footer className="mx-auto flex w-full max-w-[1240px] justify-between border-t border-[hsl(var(--border))] pt-4 font-mono text-[9px] uppercase tracking-[.12em] text-dim"><span className="flex items-center gap-2"><Wifi size={11} /> channel encrypted</span><span className="flex items-center gap-2"><ShieldCheck size={11} /> operator protocol 4.8</span></footer></main>;
}
export function Label({ children }: { children: ReactNode }) { return <div className="font-mono text-[10px] uppercase tracking-[.14em] text-dim">{children}</div>; }
export function Timer({ seconds, danger = false }: { seconds: number; danger?: boolean }) { const mins = Math.floor(seconds / 60).toString().padStart(2, '0'); const secs = (seconds % 60).toString().padStart(2, '0'); return <span className={`font-mono text-lg tracking-[.08em] ${danger ? 'text-breach' : 'text-[#d8d0bb]'}`}>{mins}:{secs}</span>; }
export function Button({ children, onClick, variant = 'primary', disabled = false, testId }: { children: ReactNode; onClick?: () => void; variant?: 'primary' | 'quiet' | 'danger'; disabled?: boolean; testId: string }) { const styles = { primary: 'bg-[#d8d0bb] text-[#111719] border-[#d8d0bb] hover:bg-[#ede7d8]', quiet: 'bg-transparent text-[#d8d0bb] border-[hsl(var(--border))] hover:border-[#849890]', danger: 'bg-transparent text-[#d07068] border-[#773434] hover:border-[#b64a46]' }; return <button data-testid={testId} type="button" onClick={onClick} disabled={disabled} className={`system-button min-h-10 border px-4 font-mono text-[10px] uppercase tracking-[.12em] disabled:cursor-not-allowed disabled:opacity-40 ${styles[variant]}`}>{children}</button>; }
